name: Crear rama
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version a crear
        required: true
        default: '0.0.1'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Version
        run: |
          version="${{ github.event.inputs.version }}"
          echo "se ha creado $version"

      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Ver archivos
        run: ls -la
      